services:
  - type: web
    name: instadoctor
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: ASSISTANT_ID
        sync: false
      - key: SECRET_KEY
        generateValue: true
